[book]
authors = [
    "Oleksandr Zarudnyi",
]
language = "en"
src = "src"
title = "solx Compiler Documentation"

[output.html]
additional-js = ["js/version-box.js"]
additional-css = ["css/version-box.css"]
